version: '3.9'

services:
  web:
    build: .
    command: sh -c "gunicorn mywebsite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend  

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - my-demo-website-develop_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DB_HOST: db  # Use service name of the database container
      PGADMIN_DB_PORT: 5432  # Use the port exposed by the database container
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - my-demo-website-develop_pgadmin_data:/var/lib/pgadmin  # uchova data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - my-demo-website-develop_static:/code/static  # pridane kvoli statickym suborom
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:

volumes:
  my-demo-website-develop_postgres_data:
  my-demo-website-develop_pgadmin_data:
  my-demo-website-develop_static:
